version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: node_api
    ports:
      - "3333:3333"
    depends_on:
      - db

  db:
    image: "bitnami/postgresql:latest"
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: api
    volumes:
      - database:/var/lib/postgresql/data


volumes:
  database: